name: Update News

on:
  schedule:
    - cron:  '15 1,7,14 * * *'


jobs:
   Updates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Update
        run: |
          curl https://kbd.herokuapp.com/update
