name: Update News

on:
  schedule:
    - cron:  '15 2,8,14 * * *'


jobs:
   Updates:
    runs-on: ubuntu-latest

    steps:
      - name: Update
        run: |
          curl https://kbd.herokuapp.com/update
